### ISSUE TITLE
更新日時を非表示にするオプションが欲しい

### ISSUE THREAD

**Issue by uhooi** [kawamataryo/lapras-card-readme#15]
素晴らしい Action のご提供ありがとうございます！
さっそく使わせていただきました↓
https://twitter.com/the_uhooi/status/1604108294314160128

LAPRAS Card の更新時、更新日時が文字列で表示されてしまうのが気になります。
非表示にするオプションがあると嬉しいです！

**Comment by kawamataryo** [comment]
@uhooi 

おお！！嬉しいです！
ありがとうございます！！

`v1.2.1` で更新日時を非表示にするOption追加しました 👍 
uhooiさんのREADMEにPR出してるのでご確認ください〜

**Comment by uhooi** [comment]
早過ぎる…ありがとうございます！！！
PR も確認してマージさせていただきました 🙏
