### ISSUE TITLE
README.mdのファイル名を指定できるパラメーターの追加について

### ISSUE THREAD

**Issue by bun913** [kawamataryo/lapras-card-readme#43]
## 何が問題なのか

初めまして！いつも記事を拝見したり、OSSを利用させていただいております！

このGitHub Actions を利用するにあたって、以下の部分でREADMEのファイル名をREADME.md として固定にしているかと思います。

https://github.com/kawamataryo/lapras-card-readme/blob/6cad87c944e82500dcf4af2ecf012f2776e8a155/src/lib/fetchPrevReadmeContents.ts#L8

これについて、利用者側で任意のファイル名を指定できるように機能を追加したいと考えています！

## なぜしたいのか

ほとんどの場合問題ないと思うのですが、GitHubでは「Readme.md」や「readme.md」でもREADMEとしてレンダリングするようです！

参考: https://zenn.dev/ulpianus/articles/99db2a0efc7a5c

というのも、私のリポジトリのREADME.md が Readme.md になっていて、GitHub Actionsが失敗することでこの事実に気づきました！

<img width="924" alt="image" src="https://user-images.githubusercontent.com/73948280/220927518-8980700d-d36c-4807-867d-446f2ae78eed.png">

私の場合リポジトリのファイル名を修正する予定ですが、意図を持ってreadme.md などの名前にする人もいるようなので、この機能があったほうが親切かなと思いました！

差し支えなければ私の方で動作確認をしてみてPRを出させていただければと思っていますので、ご検討いただければ幸いです！

（短い時間で作ったのでクローズしてもらってももちろんOKです！）

https://github.com/bun913/bun913

**Comment by kawamataryo** [comment]
@bun913 

Issue、PRありがとうございます！！
ファイル名の件なるほど！と思いました。考慮できていなかったです..

修正嬉しいです 👍 

v1.2.4で修正を取り込んだものをリリースさせて頂きました！確認お願いします
https://github.com/kawamataryo/lapras-card-readme/releases/tag/v1.2.4

**Comment by bun913** [comment]
@kawamataryo 

ありがとうございます！

実は私も元公務員・年も近く、いつも参考にさせていただいています！

少しでもお役に少しでも立てたら嬉しい限りです！
これからもよろしくお願いします！
